[package]
name = "rustos"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23"
vgabuffer = { path = "vgabuffer" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dev-dependencies]
bootimage = "0.10.3"
