# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  install:deps:
    cmds:
      - rustup component add llvm-tools-preview rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - cargo install bootimage
      - cargo install --path .
  run:
    cmds:
      - cargo run -v
